package com.example.dordle;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;

import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.text.Layout;
import android.util.Log;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.PopupWindow;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import com.android.volley.toolbox.Volley;

import java.util.Arrays;
import java.util.Random;

public class MainActivity extends AppCompatActivity {
    LinearLayout wordle1;
    LinearLayout wordle2;
    LinearLayout wordle3;
    String words ="ABACI ABADİ ABALI ABANA ABANİ ABAŞO ABBAS ABDAL ABECE ABHAZ ABLAK ABOSA ABRAŞ ABULİ ACARA ACEZE ACICA ACUBE ACUZE ACİBE ADALE ADALI ADAMA ADANA ADEDİ ADESE ADINA ADSAL AFAZİ AFONİ AFSUN AFTOS AFŞAR AFŞİN AGAMİ AGORA AGRAF AHCAR AHFAT AHFEŞ AHLAF AHRAZ AKABE AKAJU AKALA AKDUT AKEMİ AKKUŞ AKKÖY AKLAN AKLEN AKLIK AKMAK AKMAN AKMAZ AKONT AKPAS AKTAŞ AKVAM ALAZA ALKİL ALLAH ALLEM ALMAÇ ALMAŞ ALMUS ALNAÇ ALTES ALTIK ALTIZ ALTLI ALYAN ALYON AMORF AMPER AMUDİ ANACA ANALI ANDIK ANDIZ ANELE ANGIN ANJİN ANLAK ANMAK ANSIZ ANTLI ANYON ANZAK ANÜRİ ANİDE APOTR APOŞİ APRİL APSİS ARAKA ARALI ARAMİ ARDAK ARGAÇ ARGIN ARICI ARKAÇ ARKOZ ARMUZ ARSİN ARTIN ARİYA ASKAT ASTİK ASUDE ASYÖN ATFEN ATMIK AVARA AVAZE AVRAT AVRET AVURT AYEVİ AYICI AYLAK AYLIK AYMAK AYMAZ AYNAZ AYRIK AYRIM AYRIT AYRIÇ AYSAR AYSIZ AYVAN AYVAZ AYYAR AZMAK AZNİF AZOİK AZVAY AÇMAK AĞCIK AĞMAK AĞNAM AĞRAZ AĞYAR BABAÇ BABAİ BADAL BADAS BADAT BADIÇ BADYA BAHAİ BAHRİ BAHİS BAKAM BAKAÇ BALAR BALKI BALOZ BANAK BANAZ BANJO BARAK BARBA BARCI BARDA BARDO BARKA BARÇA BARİT BASSO BASYA BASİL BATUR BAVCI BAVLI BAYRI BAZİK BAZİT BAÇÇI BAĞAN BAĞDA BAĞIL BAĞIM BAĞIN BAĞIR BAĞIT BAŞAT BECET BEDÜK BEDİK BEDİR BEDİİ BEHEY BEHRE BEKAS BEKRİ BELCE BELDE BELEK BELEN BELEŞ BELGİ BELİK BELİT BELİĞ BENCİ BENLİ BERRİ BESNİ BEZCİ BEZEK BEZGİ BEZME BEZSİ BEZİK BEZİR BEZİŞ BEŞLİ BEŞME BEŞON BEŞUŞ BICIL BIKIŞ BIKMA BIZIR BOCCE BOCUK BODUÇ BOKLU BOLCA BORAK BORİK BOYCA BOYLU BOZMA BOZUŞ BOĞAK BOĞMA BOĞUK BRÖVE BUHUR BULAK BULMA BUNCA BUNLU BUNMA BURAK BURCU BURMA BUYOT BUZCU BUZLA BUĞUR BUĞUZ BÖLEN BÖNCE BÜCÜR BÜKEN BÜKME BÜKÜK BÜKÜN BÜKÜÇ BÜKÜŞ BÜRGÜ BÜRÜK BÜRÜN BÜTEN BÜTEY BÜVET BÜZÜK BÜĞET BÜĞLÜ BİCİK BİDAR BİDAT BİHUŞ BİKES BİKİR BİLAR BİNER BİNGİ BİNME BİNİT BİRCİ BİRER BİRLİ BİRUN BİTEK BİTEY BİTLİ BİTME BİTÜM BİTİM BİTİŞ BİYEL BİZAR BİZCE BİÇKİ BİÇME BİÇİŞ BİŞEK CALİP CAMIZ CAMLI CAMSI CAMİT CARLI CARTA CAYIŞ CAYMA CAZCI CAZLI CAZİP CAİZE CEDEL CEHRE CEMAN CEVVİ CEVZA CEZRİ CICIK CIVMA CIZIK CORUM CUDAM CÜNHA CÜNUN CİCOZ CİCİK CİDAL CİHAR DALAŞ DALGI DALYA DAMAL DAMLI DANCA DANIŞ DARAÇ DARCA DATİF DAVYA DAĞCI DAĞLI DENME DERUN DEĞEÇ DIŞIK DONAM DONRA DORUM DOĞMA DULDA DURAÇ DUYUŞ DUŞAK DUŞLU DÖNME DÖŞLÜ DÜGAH DÜVEN DÜYEK DÜYUN DÜZCE DÜÇAR DÜŞME DÜŞÇÜ DİDON DİGOR DİLCE DİLCİ DİLLİ DİNCİ DİNGİ DİNLİ DİREY DİVİK DİVİT DİZİŞ DİŞİL EDVAR EFECE EFSUS EHRAM EKSİN EKSİZ EKİCİ ELGİN ELHAK ELÇEK EMMEK ENSİZ ENTEL EPOPE ERCİK ERDEN ERSİZ ERZEL ESBAK ESLEK ESRİK ESTER ESİRE ETÇİK EVLEK EVLİK EVSİN EYTAM EZİCİ EZİNÇ EĞREZ EŞHAS EŞLEM FAHUR FASKA FASİT FENCİ FENOL FERAĞ FIŞKI FLEOL FODLA FODRA FRESK FÜLÜS FÜZEN FİLAR FİLOZ FİLSİ FİLUM FİRİK FİŞKA GARAZ GARBİ GAVOT GAZAL GAZVE GEBZE GELME GELİŞ GEMRE GEVEN GEVME GROSA GUANO GÖLEK GÖLÜK GÖMEÇ GÖMÜK GÖMÜŞ GÖNCÜ GÖNEN GÖRÜM GÖYÜK GÖĞEM GÜLÜT GÜMÜL GÜNDE GÜNEÇ GÜVEZ HAHHA HAKÇA HAMLA HANAY HAPİS HARAR HARİM HARİS HASEP HASSE HASUT HASİS HATAY HAZIK HAZRO HELİS HERKE HERTZ HEZEL HEZEN HIFIZ HINIS HIRLI HOTOZ HOŞUR HUDUT HUSUF HUSYE HUTUT HİÇÇİ IHMAK ILGIM ILIMA ILTAR ISKAT IĞRIP JARSE JELOZ KALCI KALIÇ KALYA KAMAN KANIŞ KANON KAPMA KARIK KATIM KATÇI KAVAS KAVUT KAYAR KAYRA KAŞAN KELER KELES KEMHA KEMRE KENEF KEPEZ KERES KESBİ KETON KEŞAN KILIR KINLI KIPIK KIRBA KIRKI KISKA KITIK KIŞIN KOFUL KOLZA KOMAR KOPOY KORUN KOVUŞ KOŞUN KROME KULLE KUMLU KUNDA KURCA KURUT KUTAN KUVVE KUŞET KÖMBE KÖMÜŞ KÜNCÜ KÜRDİ KÜSUF KİKLA KİLSİ KİNİN KİRDE KİTİN KİZİR LAFÇI LAGAR LAGOS LAHOS LAHUT LAKOZ LAKÇI LAVTA LAÇKA LENFA LENTO LETÇE LEÇEK LOGOS LİBAS LİBOŞ LİKEN LİNET LİNİN MAGRİ MAHIV MAHRA MAHUT MAKSİ MAKTU MALAK MALAZ MAMAK MAMBO MAMUL MANAS MANCA MANEN MANİA MAOCU MARDA MARON MASTI MASUN MAİLE MEBİZ MEHLE MEMBA MEREK MERES METİS MEVDU MEVTA MEZON MEZRU MEŞUM MOPET MORTO MUHİK MULAJ MUTÇU MUZSU MUŞLU MÜFİT MÜMAS MÜŞİR MİKOZ MİLEL MİSEL MİTİL MİYAR NADİM NAHAK NAKIS NAKIZ NASIP NASİR NEDBE NEFHA NEFTİ NEKRE NESEP NESİÇ NEZİR NOKRA NOTAM NUKUT NUMEN NURLU NİKAP NİSAP ODEON OFSET OLÇUM OMBRA ORKİT ORİON OTSUZ OYDAŞ PADOK PAUNT PAYEN PAYET PAYLI PAÇAL PENES PEÇİÇ PEŞLİ PIRTI POLKA POMAT PONJE PORNO POYRA PRAFA PRESE PÖÇÜK PÜSÜR PİNES PİRİT PİSİN RAFİT RAKİK RAKİT RATIP RAYBA REMEL REMİL REMİZ RUHÇA RUJLU RUNİK RÜYET SADIR SADME SAHAN SAKİM SALİK SANEM SANGI SAPKI SARIZ SARİG SARİH SATIM SATİR SAVLA SAVLO SAVUR SAYMA SAĞCI SAĞIM SAĞIN SAĞMA SAĞRI SEBEN SEFİH SELEF SELVA SENEK SENİR SEPEK SERİŞ SESÇİ SETER SETRE SEZİŞ SIHRİ SIKIT SIMAK SIZAK SIĞLA SOKUM SOKUŞ SOLMA SONAT SORİT SOYKA STENO STİLO SUARE SUBYE SUCUL SUDAK SUNGU SUPAP SUSUZ SUVAT SÖKÜN SÖNME SÖVÜŞ SÜNME SÜRUR SÜSEN SÜYÜM SİFİN SİLAJ SİLİŞ SİRMO SİTİL SİİRT TACİL TACİZ TAKSA TAMİK TAPIŞ TAPMA TARAZ TAVAS TAVİK TAYGA TEPKE TEPİR TERKİ TESİT TEVDİ TEVZİ TEVİL TIKIM TIKMA TIRIK TOKYO TORUL TOYGA TUMBA TVİST TÜNME TÜRAP TÜYME TİRLE TİRŞE URBAN USANÇ USARE UYMAZ VARDA VARTO VELUR VERDİ VERİT VEÇHE VURAÇ VÜRUT VÜSAT VİGLA VİTİR VİYAK YABGU YARAK YARDA YASMA YATMA YAVSI YAZIŞ YAĞAR YAŞÇA YEDME YELLİ YEREY YEVMİ YOLUK YUNAK YURDU YUTUŞ YÜLÜK YÜSRÜ YİRİK ZAHİT ZAMLI ZAMME ZARCI ZARSI ZARTA ZEBAN ZEBUN ZEBUR ZECRİ ZECİR ZEFİR ZEHAP ZEKER ZELVE ZELİL ZENCİ ZERDE ZIHLI ZIMNİ ZLOTİ ZORCA ZORGU ZORUN ZÜBDE ZÜHAL ZÜHUL ZÜKAM ZÜLAL ZÜRRA ZÜYUF ZİFAF ZİFOS ZİHAF ZİHİN ZİKİR ZİLLİ ZİMMİ ÇABUK ÇAMAT ÇAMÇA ÇANDI ÇAPLI ÇAPMA ÇATAK ÇAĞMA ÇAŞIT ÇELEK ÇEMİÇ ÇEMİŞ ÇENEK ÇENET ÇEPİN ÇIDAM ÇIFIT ÇIKAK ÇIRAĞ ÇIVMA ÇOKÇU ÇORLU ÇOTUK ÇULCU ÇULHA ÇUMRA ÇUŞKA ÇÖKÜM ÇÖRKÜ ÇÖZÜŞ ÇÖĞME ÇÖĞÜR ÇİMEK ÇİMME ÇİPİL ÇİĞDE ÇİĞİT ÖLGÜN ÖNEZE ÖNSEL ÖRGEN ÖZDEK ÖZSEL ÜFLEÇ ÜREMİ ÜÇTAŞ ÜŞENÇ ÜŞMEK İCBAR İFHAM İHATA İHDAS İLKİN İLZAM İMBİK İMLİK İNFAK İNTAK İNTAN İNTAÇ İSPİT İZAFE İZALE İÇİCİ İŞRET İŞYAR ŞARKİ ŞAVUL ŞAYKA ŞEHLA ŞEKLİ ŞEMSE ŞERHA ŞERİK ŞIRAK ŞİŞLİ ABAZA ABONE ABİDE ABİYE ACABA ACELE ACEMİ ACILI ACIMA ADETA ADRES ADSIZ AFAKİ AFGAN AFYON AFİFE AFİLİ AFİŞE AHALİ AHBAP AHENK AHKAM AHLAK AHLAT AHMAK AHVAL AHİZE AHŞAP AJANS AJİTE AKAİT AKBAŞ AKICI AKKOR AKORT AKRAN AKREP AKSAK AKSAM AKSAN AKSON AKTAR AKTÖR AKTİF AKÇIL AKİDE AKŞAM AKŞIN ALACA ALAKA ALARM ALBAY ALBÜM ALENİ ALEVİ ALEYH ALGIN ALICI ALKAN ALKIM ALKIŞ ALKOL ALLIK ALMAK ALMAN ALTIN ALÇAK ALİZE AMADE AMBAR AMBER AMELE AMELİ AMPUL AMPİR AMİGO ANANE ANCAK ANDAÇ ANDIÇ ANEMİ ANGIÇ ANGUT ANKET ANLAM ANLIK ANONS ANTEN ANTET ANTRE ANTİK ANİME APACI APLİK APORT APTAL APİKO ARABA ARABİ ARACI ARAMA ARAZİ ARDIL ARDIÇ ARENA ARGIT ARGON ARIZA ARIZİ ARKIT ARMUT AROMA ARPEJ ARPÇI ARSIZ ARTER ARTIK ARTIM ARTIŞ ARTMA ARTÇI ARİFE ARİZA ARŞIN ARŞİV ASABİ ASHAP ASILI ASKER ASKLI ASLAN ASLEN ASLIK ASMAK ASPUR ASTAR ASTAT ASTIM ASİDE ASİST ATAMA ATARİ ATAŞE ATICI ATILI ATLAS ATLET ATMAK AVANE AVANS AVARE AVDET AVLAK AVUNÇ AVİZE AVŞAR AYDIN AYGIR AYGIT AYIRT AYNEN AYRAN AYRAÇ AYYAŞ AYYUK AZADE AZAMİ AZERİ AZGIN AZILI AZLIK AZMAN AZİZE AÇGÖZ AÇLIK AÇMAZ AĞILI AĞLAK AİDAT AŞAMA AŞARİ AŞAĞI AŞEVİ AŞICI AŞILI AŞIRI AŞKIN AŞLIK AŞMAK AŞURE AŞİNA BACAK BADEM BADİK BAFRA BAGAJ BAGET BAHAR BAHÇE BAHİR BAKAN BAKIM BAKIR BAKIŞ BAKLA BAKMA BAKİR BALAT BALCI BALDO BALET BALIK BALLI BALON BALTA BALYA BALİĞ BAMBU BAMYA BANAL BANDO BANKA BANKO BANMA BANYO BARAJ BARAN BAREM BARET BARIŞ BARIŞ BAROK BARON BARUT BARİZ BASAK BASAR BASEN BASIK BASIM BASIN BASIŞ BASKI BASMA BASTI BASUR BASİT BATAK BATAR BATIK BATIL BATIN BATIŞ BATKI BATMA BATON BATİK BAVUL BAYAN BAYAT BAYIR BAYMA BAZAL BAZEN BAĞCI BAĞIŞ BAĞLI BAŞAK BAŞKA BAŞLI BAŞTA BAŞÇI BEBEK BEDEL BEDEN BEGÜM BEHER BEKAR BEKÇİ BELGE BELKİ BELLİ BEMOL BENCE BENDE BENEK BENGİ BENİZ BERAT BERİL BESTE BESİN BETER BETON BETİK BETİM BEYAN BEYAZ BEYZİ BEYİN BEYİT BEZEN BEŞER BEŞİK BEŞİZ BIDIK BIYIK BIÇAK BIÇIK BIÇKI BLOKE BOBİN BODUR BOHEM BOHÇA BOMBA BOMBE BORAN BORAT BORDA BORDO BORSA BORUK BOYAR BOYNA BOYOZ BOYUN BOYUT BOZCA BOZUK BOZUM BOĞAZ BOĞUM BRANŞ BRAVO BRONZ BRONŞ BUCAK BUDAK BUDUN BUGÜN BUHAR BUKET BUKLE BULGU BULUT BULUŞ BUNAK BURGU BURSA BURUK BURUN BUTLU BUTON BUTİK BUYMA BUZLU BUZUL BUÇUK BUĞRA BUŞON BÖBÜR BÖCEK BÖLGE BÖLME BÖLÜK BÖLÜM BÖLÜT BÖLÜŞ BÖREK BÖYLE BÖĞÜR BÜKÜM BÜLUĞ BÜNYE BÜTAN BÜTÇE BÜTÜN BÜYÜK BÜZGÜ BÜZME BİBER BİBLO BİDON BİLEK BİLET BİLGE BİLGİ BİLME BİLYE BİLİM BİLİR BİLİŞ BİNDİ BİNEK BİNİŞ BİRAZ BİREY BİRİM BİTAP BİTKİ BİTİK BİZON BİÇEM BİÇİM CACIK CADDE CAHİL CAMCI CAMİA CANAN CANLI CANİK CANİP CASUS CEBEL CEBRİ CEBİN CEBİR CEDRE CEDİT CEHRİ CEHİL CEKET CELAL CELBE CELEP CELSE CELİL CEMAL CEMRE CEMİL CENAH CENAP CENUP CENİN CEPHE CEPÇİ CEREN CESET CESUR CESİM CEVAP CEVAZ CEVİR CEVİZ CEZAİ CEZBE CEZVE CEZİR CIBIL CILIZ CIVIK CONTA COŞKU COŞMA COŞUM COŞUŞ CUKKA CUMBA CUNDA CUNTA CUŞİŞ CÜBBE CÜCÜK CÜLUS CÜMLE CÜNÜP CÜRET CÜRUF CÜRÜM CÜSSE CİBRE CİBİN CİCİM CİDAR CİDDİ CİHAN CİHAT CİHAZ CİHET CİLVE CİMRİ CİNAS CİNAİ CİNCİ CİNLİ CİNSİ CİRİM CİRİT CİSİM CİVAN CİVAR CİZRE CİZYE CİĞER DADAY DADAŞ DAHİL DAKİK DALAK DALAN DALGA DALIZ DALIŞ DALLI DALMA DALSI DAMAK DAMAR DAMAT DAMGA DAMLA DARAŞ DARBE DASİT DATÇA DAVAR DAVET DAVUL DAYAK DAĞAR DAİMA DAİMİ DAİRE DEBBE DEBİL DEFNE DEFİN DEGAJ DEKAN DEKAR DEKOR DELGİ DELME DELTA DELİK DELİL DEMCİ DEMEK DEMET DEMEÇ DEMLİ DEMRE DEMİN DEMİR DENEK DENET DENEY DENGE DENLİ DENYO DENİM DENİZ DEPAR DERBİ DERGİ DERME DERYA DERİK DERİN DESEN DESTE DETAY DEVAM DEVCE DEVRE DEVRİ DEVİM DEVİR DEYİM DEYİŞ DEĞER DEĞER DEĞME DEĞİL DEĞİM DEĞİN DEĞİŞ DEİST DEİZM DEŞME DEŞİK DILAK DIĞAN DIŞKI DOBRA DOGMA DOKUZ DOLAK DOLAM DOLAP DOLAR DOLAY DOLGU DOLMA DOLUM DOLUŞ DOMUR DOMUZ DONLU DONMA DONUK DONÖR DORSE DORUK DOSYA DOYGU DOYMA DOYUM DOYUŞ DOZAJ DOZER DOĞAL DOĞAN DOĞAÇ DOĞRU DOĞUM DOĞUŞ DRAJE DRAMA DUACI DUALI DUBAR DUBLE DUDAK DUHUL DULUK DUMAN DUMUR DURAK DURAL DURGU DURMA DURUK DURUM DURUŞ DUTÇU DUVAK DUVAR DUYAR DUYGU DUYMA DUYUM DÖGER DÖKME DÖKÜK DÖKÜM DÖKÜŞ DÖLEK DÖLÜT DÖNEK DÖNEL DÖNEM DÖNER DÖNEÇ DÖNGÜ DÖNÜK DÖNÜM DÖNÜT DÖNÜŞ DÖPER DÖVEÇ DÖVME DÖVÜŞ DÖVİZ DÖŞEK DÖŞEM DÜBEL DÜBEŞ DÜDEN DÜDÜK DÜMEN DÜNKÜ DÜNYA DÜNÜR DÜNİT DÜRME DÜRTÜ DÜRZÜ DÜRZİ DÜRÜM DÜVEL DÜVER DÜZEM DÜZEN DÜZEY DÜZEÇ DÜZGÜ DÜZME DÜĞME DÜĞÜM DÜĞÜN DÜŞES DÜŞEY DÜŞEŞ DÜŞKÜ DÜŞÜK DÜŞÜN DÜŞÜT DÜŞÜŞ DİBEK DİCLE DİDAR DİDİM DİKEL DİKEN DİKEY DİKEÇ DİKME DİKSE DİKTA DİKTE DİKÇE DİKİM DİKİT DİKİZ DİKİŞ DİLEK DİLME DİLSİ DİLİM DİLİŞ DİMAĞ DİNAR DİNCE DİNEK DİNEN DİNGO DİNME DİNİŞ DİPLİ DİREK DİREN DİRİL DİRİM DİRİĞ DİSKO DİTME DİVAL DİVAN DİYAR DİYET DİYEZ DİYOT DİZEK DİZEL DİZEM DİZEY DİZGE DİZGİ DİZME DİZİM DİZİN DİĞER DİŞLİ DİŞÇİ EBCET EBEDİ EBELİ EBLEH ECDAT EDALI EDEBİ EDİNÇ EFDAL EFEKT EFKAR EFLAK EFRAT EFRİZ EFSUN EGALE EGLOG EGZOZ EHVEN EJDER EKLEM EKLER EKMEK EKOSE EKRAN EKSEN EKSER EKSİK EKÜRİ EKİLİ ELBET ELCİK ELDEN ELEJİ ELEME ELLİK ELMAS ELMEK ELVAN ELYAF ELZEM ELÇİM ELİFİ ELİPS EMARE EMAYE EMCEK EMCİK EMLAK EMLİK EMMEÇ EMRAZ EMSAL EMTİA EMVAL EMZİK EMİCİ ENAYİ ENCAM ENDAM ENDER ENEME ENEZE ENFES ENGEL ENGİN ENKAZ ENLEM ENSAR ENZİM ENÖTE EOSEN EPEYİ EPSEM ERBAA ERBAP ERBAŞ ERBİN ERCİŞ ERDEK ERDEM ERGEN ERGİN ERKAN ERKEK ERKEN ERKEÇ ERKLİ ERKİN ERLİK ERMEK ERMİN ERMİŞ EROİN ERVAH ERZAK ERZİN ERİKA ERİME ERİNÇ ESAME ESANS ESASİ ESBAP ESEME ESHAM ESKİL ESKİZ ESLAF ESMEK ESMER ESNAF ESNEK ESPAS ESPRİ ESRAR ESSAH ESTET ESVAP ETENE ETFAL ETKEN ETKİN ETLİK ETMEK ETMEN ETNİK ETRAF ETSEL ETSİZ ETÇİL EVAZE EVCEK EVCİK EVCİL EVDEŞ EVGİN EVHAM EVKAF EVLAT EVRAK EVRAT EVREN EVRİK EVRİM EVSAF EVSİZ EVVEL EVİYE EYLEM EYLÜL EYVAH EYVAN EYYAM EZANİ EZBER EZELİ EZGİN EZGİÇ EZMEK EZİNE EÇHEL EĞLEK EĞMEK EĞMEÇ EĞMÜR EĞRİM EŞARP EŞKAL EŞKİN EŞLEK EŞLİK EŞMEK EŞRAF EŞREF EŞSİZ FACİA FAGOT FAHRİ FAHTE FAHİŞ FAKAT FAKÜL FAKİH FAKİR FALAN FALCI FALEZ FALSO FALYA FANTA FANTİ FANUS FANYA FARAD FARAŞ FARBA FARİL FARİĞ FASET FASIK FASIL FASLI FASON FASİH FATSA FATİH FAUNA FAYDA FAZIL FAZLA FECİR FEDAİ FEHVA FEHİM FEKÜL FELAH FELEK FENER FENNİ FENİK FERAH FERDA FERDİ FERLİ FERMA FERİH FERİK FESAT FESİH FETHA FETVA FETÜS FETİH FETİŞ FEVRİ FEYİZ FIKIH FIKRA FIRIN FIRKA FIRÇA FITIK FITRİ FLAMA FLORA FLORİ FLÖRE FLÖRT FODUL FOKUS FOLYO FONDA FONDÜ FONEM FORMA FOROZ FORSA FORTE FORUM FOSİL FRANK FRAPE FRENK FREZE FRİGO FRİSA FUAYE FUHUŞ FUJER FULAR FULYA FUNDA FURYA FÜNYE FÜSUN FÜTUR FİBER FİDAN FİDYE FİFRE FİGAN FİGÜR FİKRİ FİKİR FİLAN FİLET FİLİZ FİNAL FİNCE FİNİŞ FİRAK FİRAR FİREZ FİRMA FİSKE FİSTO FİTNE FİTRE FİTÇİ FİTİL FİTİN FİYAT FİZİK FİİLİ FİŞEK FİŞLİ GABRO GABYA GABİN GADİR GAFUR GAFİL GALAT GALON GALOP GALOŞ GALİP GALİZ GAMBA GAMET GAMLI GAMZE GARAJ GAROZ GARİP GASİL GAUSS GAVUR GAYDA GAYET GAYRI GAYRİ GAYUR GAYYA GAZAP GAZEL GAZLI GAZOZ GAİLE GAİTA GAŞİY GEBEŞ GEBRE GEDME GEDİK GEDİZ GELEN GELİN GELİR GENEL GENOM GENİZ GENİŞ GEOİT GEREK GEREN GEREÇ GERGİ GERME GERZE GERÇİ GERİM GERİZ GERİŞ GETTO GEVAŞ GEVİŞ GEYVE GEYİK GEYŞA GEZME GEZİŞ GEÇEK GEÇEN GEÇER GEÇME GEÇÇE GEÇİM GEÇİT GEÇİŞ GICIK GICIR GIDIK GIDIM GIPTA GIRLA GIYAP GLASE GNAYS GOCUK GODOŞ GOLCÜ GOLLÜ GONCA GORİL GOTÇA GOTİK GRADO GRENA GROGİ GRİZU GUATR GUDDE GUGUK GULAŞ GULET GURME GURUP GURUR GUSTO GUSÜL GÖBEK GÖBEL GÖBÜT GÖCEN GÖDEN GÖDEŞ GÖKÇE GÖLET GÖLGE GÖMME GÖMÜT GÖNYE GÖNÜL GÖREV GÖRGÜ GÖRME GÖRÜŞ GÖVDE GÖVEK GÖVEL GÖVEM GÖYME GÖZCÜ GÖZDE GÖZER GÖZGÜ GÖZLÜ GÖÇER GÖÇME GÖÇÜK GÖÇÜM GÖÇÜŞ GÖĞÜS GÜBRE GÜBÜR GÜCÜK GÜCÜN GÜDEK GÜDÜK GÜDÜL GÜDÜM GÜFTE GÜLCÜ GÜLEÇ GÜLLE GÜLLÜ GÜLME GÜLÜK GÜLÜŞ GÜMEÇ GÜMÜŞ GÜNAH GÜNCE GÜNEY GÜNEŞ GÜNLÜ GÜPÜR GÜRCÜ GÜREŞ GÜRSU GÜRUH GÜRÜN GÜTME GÜVEN GÜVEN GÜVEÇ GÜZEL GÜZEY GÜZÜN GÜÇLÜ GÜĞÜM GİDER GİDON GİDİŞ GİRAY GİRDİ GİREN GİRME GİRİM GİRİŞ GİTAR GİTME GİYME GİYSİ GİYİM GİYİT GİYİŞ GİZEM GİZLİ GİZİL HABBE HABER HABEŞ HABİP HABİS HACET HACİM HACİR HACİZ HADDE HADIM HADİM HADİS HAFIZ HAFTA HAFİF HAFİK HAFİT HAHAM HAKAN HAKAS HAKEM HAKLI HAKİM HAKİR HALAS HALAT HALAY HALAÇ HALEF HALEL HALEN HALET HALFA HALKA HALUK HALİK HALİM HALİS HALİÇ HAMAK HAMAL HAMAM HAMEL HAMIZ HAMLE HAMSE HAMSİ HAMUR HAMUT HAMİL HAMİŞ HANAK HANCI HANDE HANEK HANGİ HANIM HANUT HANYA HAPAZ HAPÇI HAPŞU HARAM HARAP HARAÇ HARBE HARBİ HAREM HARIM HARIN HARLI HARTA HARİR HARİÇ HASAR HASAT HASBİ HASET HASIL HASIM HASIR HASPA HASSA HASTA HATIL HATIR HATMİ HATTA HATUN HATİF HATİM HATİP HAVAN HAVAS HAVAİ HAVLI HAVLU HAVRA HAVSA HAVUT HAVUZ HAVUÇ HAVVA HAVYA HAVZA HAYAL HAYAT HAYBE HAYCI HAYDA HAYDİ HAYFA HAYIF HAYIR HAYIT HAYIZ HAYLİ HAYTA HAZAN HAZAR HAZCI HAZIM HAZIR HAZNE HAZİN HAÇLI HAİLE HAŞAT HAŞIL HAŞİN HAŞİR HAŞİV HAŞİŞ HECİN HEDEF HEDER HEDİK HEKİM HELAK HELAL HELEN HELKE HELME HELVA HELİK HEMEN HEMPA HEMZE HENÜZ HEPSİ HEREK HERZE HERİF HERİK HESAP HEVES HEYBE HEYET HIMIŞ HIRBO HIRKA HISIM HIYAR HIZAR HIZIR HIZLA HIZLI HIZMA HIŞIM HIŞIR HODAN HODRİ HOKEY HOKKA HONAZ HOPPA HORON HOROZ HORST HOZAN HOZAT HOŞAF HOŞÇA HUKUK HULUL HULUS HUMAR HUMMA HUMOR HUMUS HURDA HURMA HURRA HURUÇ HUSUL HUSUS HUTBE HUYLU HUZUR HÖDÜK HÖYÜK HÜCRE HÜCUM HÜKMİ HÜKÜM HÜLLE HÜLYA HÜNER HÜNSA HÜRLE HÜRYA HÜSÜN HÜYÜK HÜZME HÜZÜN HİCAP HİCAZ HİCRİ HİCİV HİDRA HİDİV HİKEM HİLAF HİLAL HİLAT HİLYE HİMEN HİNDU HİNDİ HİPPİ HİSAR HİSLİ HİSSE HİSSİ HİTAM HİTAN HİTAP HİTİT HİZAN HİZİP ILGAR ILGAZ ILGIN ILICA ILICA IRAMA IRGAT IRKÇI IRMAK ISLAH ISLAK ISLIK ISRAR ISSIZ ISTAR ITLAK ITRAH IZGIN IZRAR IĞDIR IŞIMA IŞKIN IŞTIR JAKAR JAPON JETON JOKER JOKEY JÜPON JİKLE JİLET KABAK KABAN KABIZ KABLO KABUK KABUL KABUS KABZA KABİL KABİN KABİR KADAR KADEH KADEM KADER KADIN KADRO KADÜK KADİM KADİR KADİT KAFES KAFUR KAFİR KAGİR KAHIR KAHPE KAHTA KAHVE KAHYA KAHİL KAHİN KAHİR KAKAO KAKAÇ KAKIM KAKIÇ KAKIŞ KAKMA KAKÜL KALAK KALAN KALAS KALAY KALBİ KALEM KALFA KALIK KALIM KALIN KALIP KALIT KALIŞ KALMA KALÇA KAMER KAMET KAMGA KAMIŞ KAMUS KAMÇI KAMİL KANAL KANAT KANCA KANIK KANIT KANKA KANLI KANMA KANTO KANUN KANİŞ KAPAK KAPAN KAPIŞ KAPLI KAPUT KAPUZ KAPİK KAPİŞ KARAR KARAY KARGA KARGI KARGO KARHA KARIN KARIŞ KARLI KARMA KARNE KARNİ KARST KARUN KARYE KARŞI KASAP KASEM KASET KASIK KASIM KASIR KASIT KASKO KASLI KASMA KASNI KASTİ KASİS KATAR KATIK KATIR KATKI KATLI KATMA KATOT KATRE KATİL KATİP KAVAF KAVAK KAVAL KAVAT KAVGA KAVKI KAVMİ KAVUK KAVUN KAVUZ KAVİL KAVİM KAVİS KAYAK KAYAN KAYAÇ KAYGI KAYIK KAYIN KAYIP KAYIR KAYIT KAYIŞ KAYMA KAYME KAYŞA KAZAK KAZAN KAZAZ KAZIK KAZIL KAZIM KAZMA KAÇAK KAÇAR KAÇIK KAÇIŞ KAÇLI KAÇMA KAÇTA KAĞAN KAĞIT KAĞNI KAİDE KAİME KAŞAR KAŞIK KAŞLI KAŞİF KEBAN KEBAP KEBZE KEBİR KEDER KEFAL KEFEN KEFNE KEFİL KEFİR KEHLE KEKEÇ KEKRE KEKİK KELAM KELEK KELEM KELEP KELEŞ KELLE KELLİ KELİK KEMAH KEMAL KEMAN KEMER KEMİK KENAR KENDİ KENET KENYA KEPEK KEPME KEPÇE KEPİR KERDE KEREM KERKİ KERTE KERTİ KERİH KERİM KERİZ KESAT KESEK KESEL KESEN KESER KESKİ KESME KESRE KESİF KESİK KESİM KESİN KESİR KESİT KESİŞ KETAL KETEN KETUM KEVEL KEVEN KEYFİ KEYİF KEŞAP KEŞEN KEŞKE KEŞKİ KEŞİF KEŞİK KEŞİŞ KIBLE KIDEM KILGI KILIF KILIK KILIÇ KILIŞ KILLI KILMA KIMIL KIMIZ KINIK KIPMA KIPTİ KIRAN KIRAT KIRAY KIRAÇ KIRCA KIRCI KIRIK KIRIM KIRMA KISAS KISIK KISIM KISIR KISIT KISIŞ KISKI KISMA KISMİ KISSA KITAL KITIR KIVAM KIYAK KIYAM KIYAS KIYGI KIYIK KIYIM KIYIN KIYIŞ KIYMA KIYYE KIZAK KIZAN KIZIK KIZIL KIZIŞ KIZMA KIŞIR KIŞLA KLAPA KLİMA KLİPS KLİŞE KOALA KOBAY KOBRA KODES KOFRA KOFTİ KOKAK KOKET KOKMA KOKOT KOKOZ KOKOŞ KOKUŞ KOLAJ KOLAN KOLAY KOLCU KOLEJ KOLLU KOLON KOLPO KOLSU KOLYE KOLİK KOLİT KOMBİ KOMOT KOMUT KOMÜN KOMİK KOMŞU KONAK KONDU KONMA KONSA KONUK KONUM KONUR KONUT KONUŞ KONYA KONİK KOPAL KOPMA KOPUK KOPUZ KOPUŞ KOPYA KOPÇA KOPİL KORAL KORKU KORNA KORNO KORSE KORTE KORUK KORZA KOTAN KOTON KOTRA KOVAN KOVCU KOVMA KOVUK KOYAK KOYAR KOYMA KOYUN KOYUT KOYUŞ KOZAK KOZAN KOÇAK KOÇAN KOÇMA KOĞUŞ KOŞAM KOŞAÇ KOŞMA KOŞUK KOŞUL KOŞUM KOŞUT KOŞİN KRAMP KRANK KRAVL KRAÇA KREDİ KREMA KROKİ KROŞE KRİKO KUBAT KUBBE KUBUR KUCAK KUDAS KUDUZ KUDÜM KUKLA KULAK KULAÇ KULUN KULÜP KULİS KUMAN KUMAR KUMAŞ KUMCU KUMLA KUMRU KUMSU KUMUK KUMUL KUMUÇ KUPES KUPLE KUPON KUPÜR KURAK KURAL KURAM KURAN KURGU KURMA KURNA KURON KURUL KURUM KURUŞ KURYA KURYE KUSMA KUSUR KUTLU KUTNU KUTSİ KUTUP KUTUR KUVER KUVÖZ KUYTU KUYUM KUZEN KUZEY KUZİN KUŞAK KUŞKU KUŞÇA KUŞÇU KÖFTE KÖHNE KÖKEN KÖKLÜ KÖKSÜ KÖKÇÜ KÖLÜK KÖMEÇ KÖMÜR KÖPEK KÖPRÜ KÖPÜK KÖRPE KÖRÜK KÖSEM KÖSNÜ KÖSÇÜ KÖTEK KÖYCÜ KÖYLÜ KÖÇEK KÖŞEK KÜBİK KÜFLÜ KÜFÜR KÜKRE KÜLAH KÜLEK KÜLLÜ KÜLLİ KÜLOT KÜLTE KÜLÇE KÜMES KÜNDE KÜNYE KÜPLÜ KÜRAR KÜREK KÜRSÜ KÜRİT KÜSKÜ KÜSME KÜSPE KÜSUR KÜTLE KÜTLÜ KÜTÖR KÜTÜK KÜTİN KÜVET KÜÇÜK KÜŞAT KÜŞNE KÜŞÜM KİBAR KİBİR KİFAF KİLER KİLLİ KİLÜS KİLİM KİLİS KİLİT KİLİZ KİMSE KİMYA KİMÜS KİNCİ KİNLİ KİNİK KİNİŞ KİRAZ KİREÇ KİRLİ KİRPİ KİRVE KİRİL KİRİŞ KİSVE KİTAP KİTLE KİTRE LADEN LADES LADİK LADİN LAFIZ LAFZİ LAGÜN LAHZA LAHİT LAKAP LAKİN LAMBA LAMEL LANDO LANET LANSE LAPON LARGO LARVA LASKİ LASTA LATİF LATİN LAVAJ LAVAŞ LAVUK LAYIK LAZCA LAZER LAZIM LAZUT LAÇIN LAÇİN LAĞIM LAĞIV LEDÜN LEGAL LEHÇE LEHİM LEMİS LEPRA LERZE LEVHA LEVYE LEYDİ LEYLİ LEZAR LEZİZ LEĞEN LIKIR LIĞLI LOBUT LODOS LOJİK LOKAL LOKMA LOKUM LONCA LONGA LOPUR LORTA LOTUS LOŞÇA LÖKOZ LÖPÜR LÜFER LÜGAT LÜGOL LÜMEN LÜNET LÜPÇÜ LÜTUF LÜZUM LİBRE LİDER LİFLİ LİGER LİKÖR LİKİT LİMAN LİMBO LİMON LİMİT LİPOM LİPİT LİRET LİRİK LİSAN LİSTE LİTRE LİVAR LİYAN LİZOL LİZÖZ MAADA MABAT MABET MABUT MACAR MACUN MADAM MADDE MADDİ MADEM MADEN MADER MADUN MADİK MAFYA MAFİŞ MAGMA MAHAL MAHFE MAHFİ MAHUR MAHYA MAHİR MAJÖR MAKAK MAKAM MAKAS MAKAT MAKET MAKRO MAKTA MAKUL MAKUS MALCA MALCI MALEN MALUL MALUM MALYA MALİK MAMUR MAMUT MANAT MANAV MANDA MANEJ MANGA MANGO MANTI MANTO MANTİ MANÇU MAPUS MARAL MARAZ MARKA MARKE MARKİ MARTI MARUF MARUL MARUZ MARYA MARİZ MASAJ MASAL MASAT MASKE MASNU MASON MASUM MASÖR MASÖZ MASİF MATAH MATBU MATEM MATLA MATUF MATUH MATİZ MAVAL MAVNA MAVRA MAVİŞ MAYIN MAYIS MAYNA MAZAK MAZOT MAZUR MAÇKA MAŞER MAŞUK MEBDE MEBNİ MEBUS MECAL MECAZ MECMU MECRA MECUS MEDAR MEDET MEDYA MEDÜZ MEDİH MEFUL MEHAZ MEHDİ MEHİL MEKAN MEKİK MELAL MELAS MELCE MELEK MELES MELEZ MELEŞ MELON MELUL MELUN MELİK MEMAT MEMNU MEMUL MEMUR MENFA MENFİ MENUS MENŞE MERAK MERAM MERCİ MERET MERMİ MERİH MERİÇ MESAJ MESAİ MESEL MESEN MESMU MESUL MESUT MESİH METAL METAN METBU METOT METRE METRO METİL METİN MEVKİ MEVLA MEVUT MEVZU MEVZİ MEYAN MEYUS MEYVE MEYİL MEZAR MEZAT MEZRA MEZUN MEZZO MEZÜR MEĞER MEŞBU MEŞRU MEŞİN MICIR MIGIR MIGRİ MIHLI MIRRA MISIR MISRA MOBİL MODEL MODEM MODÜL MOHER MOLAS MOLLA MOLOZ MONAT MONTE MORAL MOREN MORUK MOTEL MOTOR MOTTO MOTİF MOZAK MOĞOL MUARE MUCUK MUCUR MUCİP MUCİR MUCİT MUFLA MUHAL MUHAT MUHİL MUHİP MUHİT MUJİK MUKNİ MUKUS MUKİM MUMCU MUMLU MUMYA MUNİS MURAT MURİS MUSAP MUSIR MUSKA MUSON MUTAF MUTAT MUTKİ MUTLU MUYLU MUZIR MUZİP MUĞLA MUŞTA MUŞTU MÖBLE MÖSYÖ MÜBAH MÜDÜR MÜFTÜ MÜHRE MÜHÜR MÜHİM MÜJDE MÜLGA MÜLKİ MÜMİN MÜNŞİ MÜRAİ MÜRUR MÜRİT MÜZİK MÜZİÇ MİDYE MİKAP MİKRO MİLAS MİLAT MİLLİ MİLİM MİLİS MİMAR MİMLİ MİMİK MİNÖR MİNİK MİRAS MİRAT MİRAÇ MİRZA MİSAK MİSAL MİSİL MİSİS MİTOS MİTOZ MİYAV MİYAZ MİYOM MİYOP MİZAH MİZAN MİZAÇ MİÇEL NABIZ NACAK NADAN NADAS NADİR NAFTA NAFİA NAFİZ NAHIR NAHOŞ NAHİF NAHİV NAKDİ NAKIŞ NAKLİ NAKİL NAKİP NAKİT NAKŞİ NALAN NALIN NALÇA NAMAZ NAMLI NAMLU NAMUS NANAY NANİK NARİN NASIL NASIR NASİP NATIR NATUK NATÜR NAZAL NAZAR NAZIM NAZIR NAZLI NAZİK NAZİL NAZİR NAÇAR NAÇİZ NAĞME NAŞİR NEBAT NECAT NECİP NEDEN NEDİM NEFER NEFES NEFİR NEFİS NEFİY NEHİR NEHİY NEKES NELER NEMLİ NEMSE NEMÇE NESNE NESİH NESİL NESİM NESİR NEVİR NEYSE NEYÇE NEZLE NEZİF NEZİH NEŞET NEŞİR NISIF NODUL NODÜL NOGAY NOHUT NOKTA NONOŞ NOTER NUTUK NÖBET NÖRON NÜANS NÜFUS NÜFUZ NÜKTE NÜKUL NÜSHA NÜZUL NİCEL NİFAK NİHAN NİHAİ NİKAH NİKEL NİMET NİNNİ NİPEL NİSAN NİSAİ NİSPİ NİTEL NİYAZ NİYET NİZAM NİZİP NİÇİN NİĞDE NİŞAN OBERJ OBRUK OCUMA ODACI ODALI ODSUZ OFANS OFLAZ OFRİS OJELİ OKAPİ OKLUK OKSİT OKTAN OKTAV OKUMA OKUME OLASI OLEİK OLEİN OLGUN OLMAK OLMAZ OLMUŞ OLURU OMLET ONAMA ONGEN ONGUN ONLAR ONLUK ONMAK ONSUZ ONİKS OOSİT OPERA OPTİK ORADA ORALI ORASI ORAYA ORCİK ORFOZ ORGAN ORGCU ORLON ORMAN ORTAK ORTAM ORTAY ORTAÇ ORTEZ ORTOZ OTACI OTAMA OTLAK OTLUK OTSUL OTÇUL OTİST OTİZM OVALI OVMAK OVMAÇ OYACI OYALI OYLUM OYMAK OYNAK OYNAŞ OZMOZ OZUGA OĞLAK OĞLAN PABUÇ PAFTA PAGAN PAHAL PAKET PALAN PALAS PALAZ PALET PALTO PAMPA PAMUK PANDA PANEL PANİK PAPAK PAPAZ PAPEL PARAF PARKA PARKE PARPA PARSA PARTİ PARYA PARÇA PASAJ PASAK PASLI PASTA PASÇI PASÖR PASİF PATAK PATAL PATEN PATOZ PATİK PAYAN PAYDA PAZAR PAZEN PAÇOZ PEDAL PEDER PEKÇE PELTE PELÜR PELÜŞ PELİN PELİT PEMBE PENGÖ PENSE PENYE PENÇE PENİS PERDE PEREN PERKİ PERMA PERMİ PERON PERUK PERVA PESEK PESÜS PETEK PEYDA PEYKE PEŞTU PEŞİN PIHTI PINAR PIRPI PISMA PLAKA PLASE PLATO PLATİ PLAZA POKER POLAR POLAT POLEN POLÜM POLİM POLİP POLİS POMAK POMPA PONZA POPÇU PORTE PORTO POSOF POSTA POTAS POTUK POTUR POTİN POŞET PRAYA PRENS PROJE PROVA PRUVA PUDRA PUFLA PULCU PULLU PULSU PULUÇ PUMBA PUNTO PUSAT PUSET PUSLU PUSMA PUVAR PÜNEZ PÜREN PÜRÜZ PÜTÜR PİGME PİKAJ PİKAP PİKET PİLAV PİLLİ PİLOT PİLİÇ PİNEL PİNTİ PİPET PİSİK PİTON PİYAN PİYAZ PİYES PİYON PİZZA PİŞEK PİŞME PİŞTİ PİŞİK PİŞİM RABIT RACON RADAR RADDE RADON RADYO RAFLI RAFYA RAGBİ RAHAT RAHLE RAHNE RAHİM RAHİP RAKAM RAKET RAKIM RAKOR RAKUN RAKİP RALLİ RAMAK RAMPA RANDA RANZA RAPOR RASAT RASIT RASPA RASYO RAUNT RAYİÇ REAYA REBAP RECEP RECİM REDİF REFAH REFÜJ REFİK REHİN REJİM REKAT REKOR REKİZ RENDE RESEN RESMİ RESUL RESİF RESİM REVAK REVAN REVAÇ REVİR REVİŞ REYON REZİL REÇEL REŞME REŞİT RIZIK ROBOT RODAJ RODEO ROKET ROLCÜ ROMAN ROMEN ROSTO ROTOR ROTİL ROZET RUBAİ RUBLE RUFAİ RUGAN RUHEN RUHLU RULET RUMBA RUMCA RUMUZ RUSÇA RUTİN RÖFLE RÖGAR RÖTAR RÖTUŞ RÜESA RÜKÜN RÜKÜŞ RÜSUM RÜSUP RÜSVA RÜTBE RİCAL RİCAT RİJİT RİMEL RİNGA RİTİM RİYAL SABAH SABAN SABIK SABIR SABUH SABUN SABUR SABİT SADAK SADET SADIK SADİK SAFER SAFHA SAFRA SAFÇA SAFİR SAHAF SAHNE SAHRA SAHRE SAHTE SAHUR SAHİH SAHİL SAHİP SAKAF SAKAK SAKAL SAKAR SAKAT SAKIN SAKIT SAKIZ SAKLI SAKSI SAKİL SAKİN SAKİT SALAH SALAK SALAM SALAT SALAŞ SALCI SALEP SALGI SALIK SALLI SALMA SALON SALOZ SALPA SALSA SALTA SALTO SALUR SALVO SALYA SALÇA SALİM SALİP SAMAN SAMBA SAMSA SAMUR SAMUT SANAL SANAT SANCI SANIK SANIŞ SANKİ SANLI SANMA SANRI SAPAK SAPAN SAPIK SAPIŞ SAPLI SAPMA SARAK SARAT SARAY SARAÇ SARGI SARIK SARIM SARIŞ SARMA SARPA SASON SATEN SATHİ SATIH SATIR SATIŞ SATMA SAUNA SAVAK SAVAN SAVAT SAVAŞ SAVCA SAVCI SAVMA SAYAÇ SAYFA SAYGI SAYHA SAYIM SAYIN SAYIŞ SAYRI SAZAK SAZAN SAZCI SAZLI SAÇAK SAÇIK SAÇIŞ SAÇLI SAÇMA SAĞIR SAİKA SEANS SEBAT SEBEP SEBZE SEBİL SECDE SEDEF SEDYE SEDİR SEFER SEFİL SEFİR SEGAH SEHER SEHPA SEHİM SEHİV SEKEL SEKME SEKSİ SEKTE SEKİL SEKİZ SEKİŞ SELAM SELEK SELEN SELVİ SELİM SELİS SEMAH SEMAN SEMAİ SEMEN SEMER SEMİH SEMİZ SENCE SENET SENİT SEPET SEPYA SERAK SERAP SEREN SERGİ SERME SERUM SERVİ SERÇE SERİK SERİM SERİN SESLİ SETİK SETİR SEVAP SEVDA SEVER SEVGİ SEVME SEVİM SEVİR SEVİŞ SEYEK SEYİR SEYİS SEYİT SEZGİ SEZME SEZON SEÇAL SEÇKİ SEÇME SEÇİM SEÇİŞ SICAK SIFAT SIFIR SIHHİ SIKIM SIKMA SIKÇA SINAV SINAİ SINDI SINIF SINIK SINIR SINMA SIRAT SIRCI SIRIK SIRIM SIRLI SIRMA SIRÇA SISKA SITMA SIVIK SIYGA SIYGI SIZIŞ SIZMA SIÇAN SIÇMA SIĞIN SIĞIR SIĞMA SKALA SKİNK SLAYT SOFRA SOFTA SOKAK SOKET SOKMA SOKRA SOKUR SOLAK SOLCU SOLUK SOLUŞ SOMAK SOMON SOMUN SOMUT SOMYA SONAR SONDA SONLU SONRA SONUÇ SORGU SORMA SORTİ SORUM SORUN SORUŞ SOSİS SOYLU SOYMA SOYUM SOYUT SOYUŞ SOĞAN SOĞUK SPAZM SPERM SPREY STANT STATÜ STENT STRES STREÇ SUBAY SUBRA SUCUK SUDAN SUFLE SUKUT SULAK SULTA SULUK SUMAK SUNAK SUNMA SUNTA SUNUM SUNUŞ SUOKU SURAT SURET SURUÇ SUSAK SUSAM SUSKU SUSMA SUSTA SUSUŞ SUTAŞ SUTLU SUYUK SUÇLU SÖKEL SÖKME SÖKÜK SÖKÜM SÖKÜŞ SÖLOM SÖNÜK SÖNÜM SÖNÜŞ SÖVEN SÖVGÜ SÖVME SÖZCE SÖZCÜ SÖZDE SÖZEL SÖZLÜ SÖĞÜT SÖĞÜŞ SÜBEK SÜBUT SÜBYE SÜCUT SÜFLİ SÜKSE SÜKUN SÜKUT SÜLUK SÜLÜK SÜLÜN SÜLÜS SÜMEK SÜMEN SÜMER SÜMÜK SÜNGÜ SÜNNİ SÜPER SÜRAT SÜREK SÜREÇ SÜRFE SÜRGÜ SÜRME SÜRRE SÜRÜM SÜRÜŞ SÜSLÜ SÜSME SÜTLÜ SÜTRE SÜTSÜ SÜTUN SÜTÇÜ SÜVEN SÜVME SÜYEK SÜZEK SÜZGÜ SÜZME SÜZÜK SÜZÜŞ SÜĞME SİBOP SİCİL SİCİM SİDİK SİFON SİGAR SİHİR SİKKE SİKME SİLAH SİLGİ SİLKİ SİLLE SİLME SİLİK SİLİS SİMAV SİMGE SİMYA SİMİT SİNEK SİNLE SİNME SİNOP SİNSİ SİNÜS SİNİK SİNİR SİNİŞ SİPER SİPSİ SİREN SİRKE SİROZ SİRTO SİSLİ SİTEM SİVAS SİVRİ SİVİL SİYAH SİYAK SİYEK SİYER SİYME SİZCE SİĞİL TABAK TABAN TABLA TABLO TABUR TABUT TABYA TABİP TABİR TABİİ TACİK TACİR TADAT TADIM TADİL TAFRA TAFTA TAHIL TAHRA TAHTA TAHİN TAKAS TAKAT TAKIK TAKIM TAKKE TAKLA TAKMA TAKOZ TAKSİ TAKTİ TAKVA TAKİM TAKİP TALAK TALAN TALAS TALAZ TALAŞ TALEP TALİH TALİK TALİL TALİM TALİP TAMAH TAMAM TAMİM TAMİR TANEN TANGO TANIK TANIM TANIT TANIŞ TANRI TANİN TAOCU TAPAN TAPON TAPİR TARAF TARAK TARAŞ TARET TARIM TARLA TARTI TARİF TARİH TARİK TARİZ TASAR TASDİ TASIM TASMA TASNİ TATAR TATLI TATMA TATİL TAVAF TAVAN TAVCI TAVIR TAVLA TAVLI TAVUK TAVUS TAVİZ TAYFA TAYIN TAYİN TAYİP TAZİM TAZİP TAZİZ TAÇLI TAŞAK TAŞIL TAŞIM TAŞIT TAŞLI TAŞMA TAŞRA TAŞSI TAŞÇI TEALİ TEATİ TEBAA TEBER TECİL TECİM TEDAİ TEDİP TEHİR TEKEL TEKER TEKKE TEKLİ TEKME TEKNE TEKST TEKÇİ TEKİL TEKİN TEKİR TEKİT TELAŞ TELEF TELEK TELEM TELES TELLİ TELSİ TELVE TELİF TELİN TELİS TEMAS TEMEK TEMEL TEMPO TEMİN TEMİZ TENGE TENHA TENOR TENTE TENYA TENİS TEORİ TEPKİ TEPME TEPSİ TEPİK TEPİŞ TERAS TERBİ TEREK TERES TERFİ TERLİ TERME TERZİ TERÖR TERİM TESRİ TESTİ TESİR TESİS TETİK TETİR TEVEK TEVKİ TEVSİ TEYEL TEYZE TEYİT TEZAT TEZCE TEZEK TEZLİ TEĞET TEİST TEİZM TEŞCİ TEŞNE TEŞRİ TEŞYİ TIBBİ TIFIL TIKAÇ TIKIR TIKIZ TIMAR TINAZ TINMA TIPKI TIRAK TIRAŞ TIRIL TIRIS TOHUM TOKAT TOKAÇ TOKLU TOKUZ TOLGA TOMAK TOMAR TONAJ TONER TONGA TONLA TONLU TONOZ TONYA TONİK TOPAK TOPAL TOPAZ TOPAÇ TOPLA TOPLU TOPUK TOPUR TOPUT TOPUZ TOPÇU TOPİK TORAK TORBA TORNA TORTU TORUM TORUN TORİK TOSUN TOSYA TOTAL TOTEM TOYCA TOYCU TOZAN TOZLU TOZMA TRAFO TRAKE TRANS TRANŞ TRATA TROMP TRÖST TRİKO TUFAN TUGAY TUHAF TULUK TULUM TULUP TUMAN TUNİK TURAN TURAÇ TURBA TURBO TURFA TURNA TURNE TURNO TURTA TURŞU TUTAK TUTAM TUTAR TUTAÇ TUTKU TUTMA TUTUK TUTUM TUTUŞ TUTYA TUVAL TUYUĞ TUZAK TUZCU TUZLA TUZLU TUZSU TUĞCU TUĞLA TUĞLU TUĞRA TÖREL TÖREN TÖRPÜ TÖVBE TÖZEL TÜFEK TÜMCE TÜMEL TÜMEN TÜMEY TÜMÖR TÜMÜR TÜNEK TÜNEL TÜPLÜ TÜPÇÜ TÜRBE TÜREL TÜREV TÜRKÜ TÜRKİ TÜRLÜ TÜRÜM TÜTME TÜTSÜ TÜTÜN TÜVİT TÜYLÜ TÜZEL TÜZÜK TİFÜS TİKEL TİLKİ TİMÜS TİNER TİPİK TİRAJ TİRAN TİRAT TİRSİ TİRİT TİRİZ TİTAN TİTİZ UCUBE UKALA UKNUM ULAMA ULEMA ULUFE ULUMA UMACI UMMAK UMMAN UMUMİ UNLUK UNSUR UNVAN URGAN USKUR USSAL UTANÇ UTMAK UYARI UYGAR UYGUN UYGUR UYLUK UYMAK UYRUK UYSAL UYUMA UZAMA UZLET UZLUK UZMAN UÇARI UÇKUN UÇKUR UÇMAK UÇMAN UÇSUZ UÇUCU UĞRAK UĞRAŞ UĞRUN UŞKUN UŞŞAK VACİP VAGON VAHİM VAHİT VAHİY VAHŞİ VAKAR VAKFE VAKIA VAKIF VAKUM VAKUR VAKİT VALÖR VALİZ VANLI VAPUR VARAK VARAN VARGI VARIŞ VARMA VAROŞ VARTA VARİL VARİS VARİT VASAT VASIF VASIL VATAN VATKA VATOZ VAZIH VAŞAK VEBAL VECİH VECİZ VEDİA VEFAT VEHİM VEKİL VELET VELUT VENÜS VEREM VEREV VERGİ VERME VERİM VERİŞ VEZNE VEZİN VEZİR VICIK VOKAL VOLAN VOLTA VONOZ VOTKA VOYVO VUKUF VULVA VURGU VURMA VURUK VURUŞ VUSUL VUZUH VÜCUT VİDEO VİLLA VİRAJ VİRAL VİRAN VİRÜS VİSAL VİSKİ VİTES VİYOL VİZON VİZÖR VİŞNE YABAN YAFTA YAHEY YAHNİ YAHUT YAHŞİ YAKIM YAKIN YAKIT YAKIŞ YAKMA YAKUT YAKİN YALAK YALAN YALAZ YALIM YALIN YALIZ YALPA YALPI YAMAK YAMAN YAMAÇ YAMUK YAMÇI YANAK YANAL YANAY YANAZ YANCI YANGI YANIK YANIT YANIŞ YANKI YANLI YANMA YANSI YAPAK YAPAY YAPIK YAPIM YAPIT YAPIŞ YAPMA YARAN YARAR YARAŞ YAREN YARGI YARIK YARIM YARIN YARIŞ YARKA YARMA YASAK YASAL YASLI YASSI YASİN YATAK YATAY YATIK YATIM YATIR YATIŞ YATSI YATÇI YAVAN YAVAŞ YAVER YAVRU YAVUZ YAYAN YAYGI YAYIK YAYIM YAYIN YAYIŞ YAYLA YAYLI YAYMA YAZAR YAZGI YAZIK YAZIM YAZIN YAZIR YAZIT YAZMA YAĞCI YAĞIR YAĞIZ YAĞIŞ YAĞLI YAĞMA YAĞSI YAŞAM YAŞIT YAŞLI YEDEK YEDİZ YEGAH YEGAN YEKTA YEKUN YELEK YELEÇ YELME YELVE YELİN YEMCİ YEMEK YEMİN YEMİŞ YENGE YENGİ YENLİ YENME YENİK YEREL YERGİ YERLİ YERME YETER YETKE YETKİ YETME YETİK YETİM YEYGİ YEZİT YEĞEN YEĞNİ YEĞİN YEŞİL YEŞİM YIKIK YIKIM YIKIŞ YIKMA YILAN YILGI YILIK YILKI YILMA YIRIK YIĞIN YIĞIŞ YIĞMA YOBAZ YOKSA YOKUŞ YOKÇU YOLAK YOLCU YOLLU YOLMA YOMRA YONCA YONGA YONMA YONTU YORGA YORMA YORTU YORUM YOSMA YOSUN YOĞUN YUDUM YUFKA YUKAÇ YULAF YULAR YUMAK YUMMA YUMRU YUMUK YUNAN YUNMA YUNUS YUTAK YUTMA YUTUM YUVAK YUVAR YUVGU YÖNLÜ YÖRÜK YÜKLÜ YÜKÇÜ YÜKÜM YÜKÜN YÜLGÜ YÜNLÜ YÜREK YÜRÜK YÜZDE YÜZER YÜZEY YÜZLÜ YÜZME YÜZÜK YÜZÜŞ YİRMİ YİTME YİTİK YİTİM YİTİŞ YİVLİ YİYİM YİYİŞ YİĞİT ZABIT ZABİT ZAFER ZAFER ZAHİR ZALİM ZAMAN ZAMİR ZANKA ZANLI ZARAR ZARİF ZATEN ZAYIF ZAĞAR ZAĞCI ZAĞLI ZEBRA ZEHİR ZEKAT ZEMİN ZENNE ZERRE ZEVAL ZEVAT ZEVCE ZEYİL ZIBIN ZIMBA ZIPIR ZIPKA ZIRVA ZOMBİ ZORBA ZORLA ZORLU ZUHUR ZULÜM ZURNA ZÜHRE ZÜLÜF ZÜMRE ZÜPPE ZİFİN ZİFİR ZİGON ZİGOT ZİHNİ ZİNDE ZİRAİ ZİRVE ZİYAN ÇADIR ÇAKAL ÇAKAR ÇAKER ÇAKIL ÇAKIM ÇAKIN ÇAKIR ÇAKIŞ ÇAKMA ÇAKRA ÇALAK ÇALAP ÇALAR ÇALGI ÇALIK ÇALIM ÇALIŞ ÇALKI ÇALMA ÇALTI ÇAMAŞ ÇAMUR ÇANAK ÇANCI ÇANLI ÇANTA ÇAPAK ÇAPAR ÇAPLA ÇAPUL ÇAPUT ÇARIK ÇARKA ÇARPI ÇARŞI ÇASAR ÇATAL ÇATIK ÇATIŞ ÇATKI ÇATMA ÇAVLI ÇAVMA ÇAVUN ÇAVUŞ ÇAYAN ÇAYCI ÇAYIR ÇAYLI ÇAĞLA ÇAĞRI ÇEBİÇ ÇECİK ÇEDİK ÇEHRE ÇEKEK ÇEKEL ÇEKEM ÇEKER ÇEKME ÇEKÇE ÇEKÜL ÇEKİK ÇEKİM ÇEKİÇ ÇEKİŞ ÇELEN ÇELGİ ÇELLO ÇELME ÇELİK ÇELİM ÇEMEN ÇEMÇE ÇENGİ ÇEPEL ÇEPER ÇEPEZ ÇEPNİ ÇERAĞ ÇEREZ ÇERGE ÇERÇİ ÇETİN ÇEVRE ÇEVRİ ÇEVİK ÇEYİZ ÇEÇEN ÇEŞME ÇEŞNİ ÇEŞİT ÇIBAN ÇIKAN ÇIKAR ÇIKIK ÇIKIN ÇIKIT ÇIKIŞ ÇIKMA ÇIKRA ÇIKTI ÇINAR ÇINGI ÇIPIR ÇIRAK ÇIRPI ÇITAK ÇITIR ÇIYAN ÇIĞIR ÇOBAN ÇOCUK ÇOKAL ÇOKLU ÇOKÇA ÇOLAK ÇOLPA ÇOMAK ÇOMAR ÇOPRA ÇOPUR ÇORAK ÇORAP ÇORBA ÇORUM ÇOTRA ÇOĞUL ÇOĞUN ÇUBUK ÇUKUR ÇUPRA ÇUVAL ÇUVAŞ ÇÖKEK ÇÖKEL ÇÖKME ÇÖKÜK ÇÖKÜŞ ÇÖMEZ ÇÖMME ÇÖMÇE ÇÖPLÜ ÇÖPÇÜ ÇÖREK ÇÖRTÜ ÇÖVEN ÇÖZGÜ ÇÖZME ÇÖZÜK ÇÖZÜM ÇÜKÜR ÇÜNKÜ ÇÜRÜK ÇİFTE ÇİGAN ÇİLEK ÇİLLİ ÇİMEN ÇİNCE ÇİNKO ÇİNLİ ÇİROZ ÇİRİŞ ÇİSEN ÇİTEN ÇİTME ÇİVİT ÇİZER ÇİZGE ÇİZGİ ÇİZME ÇİZİK ÇİZİM ÇİZİŞ ÇİÇEK ÇİĞLİ ÇİĞİL ÇİĞİN ÇİŞİK ÖBÜRÜ ÖDEME ÖDLEK ÖDÜNÇ ÖKSÜZ ÖLMEK ÖLMEZ ÖLMÜŞ ÖLÇEK ÖLÇER ÖLÇME ÖLÇÜM ÖLÇÜN ÖLÇÜT ÖLÇÜŞ ÖNCEL ÖNCÜL ÖNDER ÖNERİ ÖNLEM ÖNLÜK ÖPMEK ÖRCİN ÖRDEK ÖREKE ÖRGÜN ÖRGÜT ÖRMEK ÖRNEK ÖRTME ÖRTÜK ÖRTÜŞ ÖRÜCÜ ÖRÜLÜ ÖTEKİ ÖTMEK ÖTÜCÜ ÖTÜRÜ ÖVMEK ÖVÜCÜ ÖVÜNÇ ÖZALP ÖZBEK ÖZDEN ÖZDEŞ ÖZEME ÖZENÇ ÖZENİ ÖZERK ÖZGÜL ÖZGÜN ÖZGÜR ÖZLEM ÖZLÜK ÖZNEL ÖĞLEN ÖĞREK ÜCRET ÜDEBA ÜLFET ÜLGER ÜLKER ÜLSER ÜMERA ÜMMET ÜMRAN ÜNDEŞ ÜNLEM ÜNSÜZ ÜNİTE ÜREME ÜRGÜP ÜRKEK ÜRKME ÜRKÜŞ ÜRYAN ÜRÜME ÜSERA ÜSKÜF ÜSLUP ÜSTAT ÜSTEL ÜSTLÜ ÜSTÜN ÜTMEK ÜTÜCÜ ÜTÜLÜ ÜZERE ÜZERİ ÜZGÜN ÜZLÜK ÜZMEK ÜZÜCÜ ÜZÜNÇ ÜÇGEN ÜÇGÜL ÜÇKAT ÜÇLER ÜÇLÜK ÜĞRÜM ÜŞÜME İBARE İBATE İBDAİ İBLAĞ İBLİS İBRAZ İBRET İBRİK İBZAL İCMAL İDADİ İDAME İDARE İDARİ İDDİA İDEAL İDMAN İDRAK İDRAR İFADE İFFET İFLAH İFLAS İFRAT İFRAZ İFRAĞ İFRİT İFSAT İFTAR İHALE İHBAR İHLAL İHLAS İHMAL İHRAM İHRAZ İHRAÇ İHSAN İHSAS İHTAR İHVAN İHZAR İKAME İKBAL İKDAM İKLİM İKMAL İKONA İKRAH İKRAM İKRAR İKRAZ İKSİR İKİCİ İKİLİ İLAHE İLAHİ İLAHİ İLAVE İLBAY İLENÇ İLERİ İLETİ İLGEÇ İLHAK İLHAM İLHAN İLKAH İLKEL İLLET İLMEK İLMİK İMALE İMALI İMAME İMBAT İMDAT İMECE İMKAN İMLEK İMLEÇ İMREN İMROZ İMSAK İNANÇ İNCİK İNCİL İNCİR İNDİS İNFAZ İNGİN İNKAR İNMEK İNSAF İNSAN İNZAL İNÖNÜ İNŞAT İPEKA İPHAM İPLİK İPSİZ İPTAL İPUCU İPÇİK İRADE İRADİ İRFAN İRKME İRMİK İRONİ İRSAL İRSEN İRİCE İRİTE İRŞAT İSALE İSEVİ İSHAL İSKAN İSKOÇ İSLAM İSLAV İSLİM İSMEN İSMET İSNAT İSPAT İSPİR İSPİR İSRAF İSTEK İSTEM İSTER İSTOP İSTİF İSTİM İSYAN İTAAT İTEĞİ İTHAF İTHAL İTHAM İTLAF İTLİK İTMAM İTMEK İTİCİ İTİLA İTİNA İVEDİ İVESİ İVMEK İYİCE İZABE İZAFİ İZHAR İZLEK İZLEM İZLEV İZMİR İZMİT İZNİK İZOLE İZZET İÇERİ İÇKİN İÇLEM İÇLİK İÇMEK İÇREK İÇSEL İÇSİZ İÇTEN İÇYÜZ İĞDİR İĞDİŞ İĞFAL İĞLİK İŞEME İŞGAL İŞKAL İŞKİL İŞLEK İŞLEM İŞLEV İŞLİK İŞMAR İŞSİZ İŞTAH İŞTEŞ ŞABAN ŞAFAK ŞAFUL ŞAFİİ ŞAHAP ŞAHIS ŞAHNE ŞAHSİ ŞAHİN ŞAHİT ŞAKAK ŞAKUL ŞALAK ŞAMAN ŞAMAR ŞAMİL ŞANLI ŞAPEL ŞAPKA ŞAPLI ŞAPÇI ŞARAP ŞARKI ŞARPİ ŞARYO ŞATIR ŞAYAK ŞAYAN ŞAYET ŞAYİA ŞAİBE ŞAİRE ŞAŞAA ŞAŞMA ŞEBEK ŞEDDE ŞEDİT ŞEFİK ŞEHİR ŞEHİT ŞEKEL ŞEKER ŞEKVA ŞEKİL ŞELEK ŞEMSİ ŞEPİT ŞERAN ŞEREF ŞERPA ŞERİF ŞERİR ŞERİT ŞETİM ŞINAV ŞIPKA ŞOFÖR ŞOPAR ŞORCA ŞOSET ŞOSON ŞOVEN ŞUARA ŞUBAT ŞUHUT ŞUNCA ŞURUP ŞÖLEN ŞÖMİZ ŞÖYLE ŞÜKÜR ŞÜMUL ŞÜPHE ŞİFON ŞİFRE ŞİKAR ŞİLEM ŞİLEP ŞİLTE ŞİLİN ŞİMAL ŞİMDİ ŞİNTO ŞİNİK ŞİRAN ŞİRİN ŞİŞEK ŞİŞKO ŞİŞME ŞİŞİK ";
    String[] valids = words.split(" ");
    LinearLayout wordle4;
    String word1;
    String word2;
    String word3;
    String word4;
    int[] results = new int[]{0,0,0,0};
    boolean[] iscomplete = new boolean[]{false,false,false,false};
    String[] wordarr;
    int currentrow;
    int currentchar;
    TextView[][][] wordles = new TextView[4][9][5];
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        wordle1 = findViewById(R.id.wordle1);
        wordle2 = findViewById(R.id.wordle2);
        wordle3 = findViewById(R.id.wordle3);
        wordle4 = findViewById(R.id.wordle4);

        RequestQueue queue = Volley.newRequestQueue(this);
        String url = "https://mrtrncbr-daily-words-api.herokuapp.com";
        StringRequest stringRequest = new StringRequest(Request.Method.GET, url, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {
                try {
                    JSONObject jsonRes = new JSONObject(response);
                    JSONArray wordarray= jsonRes.getJSONArray("words");
                    word1=wordarray.getString(0);
                    word2=wordarray.getString(1);
                    word3=wordarray.getString(2);
                    word4=wordarray.getString(3);
                    wordarr= new String[]{word1,word2,word3,word4};
                } catch (JSONException e) {
                    e.printStackTrace();
                }
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                Log.d("AAAAAAAAAAAA","AAAAA");
            }
        });
        queue.add(stringRequest);
        createBoard();

    }

    private void createBoard() {
        for(int z =0;z<4;z++) {
            for (int i = 0; i < 9; i++) {
                LinearLayout layout = new LinearLayout(this);
                layout.setGravity(1);
                for (int j = 0; j < 5; j++) {
                    TextView img = new TextView(this);
                    img.setBackgroundResource(R.drawable.wordle_kutu);
                    LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(60, 60);
                    img.setLayoutParams(layoutParams);
                    ViewGroup.MarginLayoutParams marginParams = (ViewGroup.MarginLayoutParams) img.getLayoutParams();
                    marginParams.setMargins(5, 5, 5, 5);
                    img.setGravity(1);
                    img.setTextColor(Color.parseColor("#FFFFFF"));
                    img.setTextSize(15);
                    wordles[z][i][j] = img;
                    layout.addView(img);
                }
                switch (z){
                    case 0:
                        wordle1.addView(layout);
                        break;
                    case 1:
                        wordle2.addView(layout);
                        break;
                    case 2:
                        wordle3.addView(layout);
                        break;
                    case 3:
                        wordle4.addView(layout);
                        break;
                }
            }
        }
    }

    public void getChar(View view) {
        TextView textView = (TextView) view;
        writeChar(textView.getText());
    }
    public void writeChar(CharSequence str){
        if (currentchar!=5) {
            if (!iscomplete[0]){
                wordles[0][currentrow][currentchar].setText(str);
            }
            if (!iscomplete[1]){
                wordles[1][currentrow][currentchar].setText(str);
            }
            if (!iscomplete[2]){
                wordles[2][currentrow][currentchar].setText(str);
            }
            if (!iscomplete[3]){
                wordles[3][currentrow][currentchar].setText(str);
            }
        }
        if (currentchar<5){
            currentchar+=1;
        }
    }

    public void enter(View view) {
        if (currentchar==5) {
            String word = "";
            for (int i = 0; i < 5; i++) {
                if (!iscomplete[0]) {
                    word += wordles[0][currentrow][i].getText();
                } else if (!iscomplete[1]) {
                    word += wordles[1][currentrow][i].getText();
                } else if (!iscomplete[2]) {
                    word += wordles[2][currentrow][i].getText();
                } else if (!iscomplete[3]) {
                    word += wordles[3][currentrow][i].getText();
                }
            }
            if (words.contains(word)) {
                boolean[] isExist = new boolean[]{false, false, false, false, false};
                for (int i = 0; i < 4; i++) {
                    Log.d("Words:", wordarr[i]);
                    int correctcount = 0;
                    if (iscomplete[i]) {
                        continue;
                    }
                    char[] wordlechar = new char[5];
                    char[] targetchar = new char[5];
                    for (int j = 0; j < 5; j++) {
                        if (wordles[i][currentrow][j].getText().charAt(0) == wordarr[i].charAt(j)) {
                            wordles[i][currentrow][j].setBackgroundResource(R.drawable.true_box);
                            correctcount += 1;
                            wordlechar[j] = '0';
                            targetchar[j] = '0';
                        } else {
                            wordles[i][currentrow][j].setBackgroundResource(R.drawable.old_kutu);
                            wordlechar[j] = wordles[i][currentrow][j].getText().charAt(0);
                            targetchar[j] = wordarr[i].charAt(j);
                        }
                        if (correctcount == 5) {
                            results[i]=currentrow+1;
                            iscomplete[i] = true;
                        }
                        for (int z = 0; z < 5; z++) {
                            for (int q = 0; q < 5; q++) {
                                if (wordlechar[z] == targetchar[q] && wordlechar[z] != '0') {
                                    wordles[i][currentrow][z].setBackgroundResource(R.drawable.false_location);
                                    wordlechar[z] = '0';
                                    targetchar[q] = '0';
                                }
                            }
                        }
                    }
                    for (int z = 0; z < 5; z++) {
                        if (wordlechar[z] == '0') {
                            isExist[z] = true;
                        }
                    }
                }

                for (int z = 0; z < 5; z++) {
                    if (isExist[z] == false) {
                        String str = String.format("%s", word.charAt(z));
                        int resID = getResources().getIdentifier(str, "id", getPackageName());
                        TextView txt = findViewById(resID);
                        txt.setBackgroundResource(R.drawable.old_kutu);
                    }
                }
                currentrow += 1;
                currentchar = 0;
            }
            int count = 0;
            for (int z = 0; z < 4; z++) {

                if (iscomplete[z]) {
                    count += 1;
                }
                if (count == 4) {
                    resultScreen();
                }
            }
            if (currentrow==9){

                resultScreen();
            }
        }
    }

    private void resultScreen() {
        LayoutInflater inflater = (LayoutInflater)
                getSystemService(LAYOUT_INFLATER_SERVICE);
        View popupView = inflater.inflate(R.layout.secondlayout, null);


        int width = LinearLayout.LayoutParams.MATCH_PARENT;
        int height = LinearLayout.LayoutParams.MATCH_PARENT;
        boolean focusable = true;
        final PopupWindow popupWindow = new PopupWindow(popupView, width, height, focusable);

        popupWindow.showAtLocation(this.findViewById(R.id.wordle1), Gravity.CENTER, 0, 0);
        TextView txt = popupView.findViewById(R.id.wordle1resulttext);
        txt.setText(String.format("%s", wordarr[0]));
        txt = popupView.findViewById(R.id.wordle2resulttext);
        txt.setText(String.format("%s", wordarr[1]));
        txt = popupView.findViewById(R.id.wordle3resulttext);
        txt.setText(String.format("%s", wordarr[2]));
        txt = popupView.findViewById(R.id.wordle4resulttext);
        txt.setText(String.format("%s", wordarr[3]));
        if (results[0]==0){
            TextView tx= popupView.findViewById(R.id.wordle4result);
            tx.setBackgroundResource(R.drawable.false_box);
        }
        else {
            TextView tx= popupView.findViewById(R.id.wordle4result);
            tx.setBackgroundResource(R.drawable.true_box);
            tx.setText(String.format("%s", results[0]));
        }
        if (results[1]==0){
            TextView tx= popupView.findViewById(R.id.wordle2result);
            tx.setBackgroundResource(R.drawable.false_box);
        }
        else {
            TextView tx= popupView.findViewById(R.id.wordle2result);
            tx.setBackgroundResource(R.drawable.true_box);
            tx.setText(String.format("%s", results[1]));
        }
        if (results[2]==0){
            TextView tx= popupView.findViewById(R.id.wordle3result);
            tx.setBackgroundResource(R.drawable.false_box);
        }
        else {
            TextView tx= popupView.findViewById(R.id.wordle3result);
            tx.setBackgroundResource(R.drawable.true_box);
            tx.setText(String.format("%s", results[2]));
        }
        if (results[3]==0){
            TextView tx= popupView.findViewById(R.id.wordle1result);
            tx.setBackgroundResource(R.drawable.false_box);
        }
        else {
            TextView tx= popupView.findViewById(R.id.wordle1result);
            tx.setBackgroundResource(R.drawable.true_box);
            tx.setText(String.format("%s", results[3]));
        }
        Button btn =popupView.findViewById(R.id.dismiss);
        btn.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View view) {
                popupWindow.dismiss();
            }
        });
        restartGame();
    }

    private void restartGame() {
        for(int z = 0; z<4; z++) {
            for(int i = 0; i<9;i++){
                for(int j = 0; j<5;j++){
                    wordles[z][i][j].setText(" ");
                    wordles[z][i][j].setBackgroundResource(R.drawable.wordle_kutu);
                    results[0]=0;
                    results[1]=0;
                    results[2]=0;
                    results[3]=0;
                    iscomplete[0]=false;
                    iscomplete[1]=false;
                    iscomplete[3]=false;
                    iscomplete[2]=false;
                    currentchar=0;
                    currentrow=0;
                }
            }
        }
    }

    public void delete(View view) {
        if(currentchar>0){
            currentchar-=1;
        }
        wordles[0][currentrow][currentchar].setText(" ");
        wordles[1][currentrow][currentchar].setText(" ");
        wordles[2][currentrow][currentchar].setText(" ");
        wordles[3][currentrow][currentchar].setText(" ");
    }

}
